---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8u191-alpine


params:
  SONARQUBE_KEY: ((sonarqube-token))
  SONARQUBE_URL: ((sonarqube-url))

inputs:
  - name: git
  - name: version

caches:
  - path: maven-cache

outputs:
  - name: build-output

run:
  path: /bin/sh
  args:
    - git/ci/tasks/build.sh
