---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8

inputs:
  - name: git

caches:
  - path: maven-cache

outputs:
  - name: build-output

run:
  path: /bin/bash
  args:
    - git/ci/tasks/build.sh
