resources:
- name: git
  type: git
  source:
    uri:  git@github.com:emerald-squad/sonar-shellcheck-plugin.git
    private_key: ((github-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:emerald-squad/sonar-shellcheck-plugin.git
    branch: master
    file: version
    private_key: ((github-key))
    initial_version: 0.1.0
    git_user: "Version bumper bot<version@bumper.bot>"
    commit_message: "[ci skip] Bumping version"
- name: release
  type: github-release
  source:
    owner: emerald-squad
    repository: sonar-shellcheck-plugin
    access_token: ((github-access-token))

jobs:
- name: build
  plan:
  - get: git
    trigger: true
  - get: version
    params:
      bump: patch
  - task: build
    file: git/ci/tasks/build.yml
  - put: version
    params:
      bump: patch
  - put: release
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      globs:
      - build-output/sonar-shellcheck-plugin*.jar