resources:
- name: git
  type: git
  source:
    uri:  git@github.com:emerald-squad/sonar-shellcheck-plugin.git
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:emerald-squad/sonar-shellcheck-plugin.git
    branch: master
    file: version
    private_key: ((github-key))
    initial_version: 0.1.0
    git_user: "Version bumper bot<version@bumper.bot>"
    commit_message: "[ci skip] Bumping version"

jobs:
- name: build
  plan:
  - get: git
    trigger: true
  - get: version
    params:
      bump: minor
  - task: build
    file: git/tasks/build.yml
  - put: version
    params:
      bump: minor